import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { firstValueFrom } from 'rxjs';
type View = 'Dashboard'|'Create'|'Library'|'Profile';
interface User { id:string;email:string;display_name:string;roles:string[];bio?:string;institution?:string }
interface Usage { daily_limit:number;used_today:number;remaining_today:number;questions_created:number }
interface Template { id:string;name:string }
interface Question { question_text:string;explanation:string;question_type:string;difficulty:string;bloom_level:string;options:{key:string;text:string}[];id?:string }
@Component({selector:'app-root',imports:[FormsModule],templateUrl:'./app.html',styleUrl:'./app.scss'})
export class App {
 private http=inject(HttpClient); protected view=signal<View>('Dashboard'); protected user=signal<User|null>(null); protected usage=signal<Usage>({daily_limit:50,used_today:0,remaining_today:50,questions_created:0}); protected loginOpen=signal(false); protected email=signal('');protected password=signal('');protected notice=signal('');protected templates=signal<Template[]>([]);protected templateId=signal('');protected query=signal('');protected difficulty=signal('Medium');protected bloom=signal('Understand');protected count=signal(3);protected generating=signal(false);protected questions=signal<Question[]>([]);protected ratingQuestion=signal<Question|null>(null);protected rating=signal(5);protected area=signal('');protected feedbackNote=signal('');protected name=signal('');protected bio=signal('');protected institution=signal('');protected currentPassword=signal('');protected newPassword=signal('');
 constructor(){void this.restoreSession()} private headers(){const t=localStorage.getItem('aug27_exam_token');return t?new HttpHeaders({Authorization:`Bearer ${t}`}):new HttpHeaders()}
 private async restoreSession(){try{this.setUser(await firstValueFrom(this.http.get<User>('/api/auth/me',{headers:this.headers()})))}catch{localStorage.removeItem('aug27_exam_token')}} private setUser(u:User){this.user.set(u);this.name.set(u.display_name);this.bio.set(u.bio||'');this.institution.set(u.institution||'');void this.loadUsage();void this.loadTemplates()} private async loadUsage(){try{this.usage.set(await firstValueFrom(this.http.get<Usage>('/api/questions/usage',{headers:this.headers()})))}catch{}} private async loadTemplates(){try{const x=await firstValueFrom(this.http.get<Template[]>('/api/templates',{headers:this.headers()}));this.templates.set(x);if(x[0])this.templateId.set(x[0].id)}catch{}}
 protected navigate(v:View){this.view.set(v);this.notice.set('');if(v==='Dashboard')void this.loadUsage()} protected async login(){try{const x=await firstValueFrom(this.http.post<{access_token:string}>('/api/auth/login',{email:this.email(),password:this.password()}));localStorage.setItem('aug27_exam_token',x.access_token);this.loginOpen.set(false);await this.restoreSession();this.notice.set('Welcome back — your studio is ready.')}catch{this.notice.set('We could not sign you in. Check your email and password.')}} protected logout(){localStorage.removeItem('aug27_exam_token');this.user.set(null);this.navigate('Dashboard')}
 protected async generate(){if(!this.user()){this.loginOpen.set(true);return}if(!this.templateId()||!this.query().trim()){this.notice.set('Choose a pattern and add a topic or source query.');return}this.generating.set(true);this.notice.set('Curating grounded questions for you…');try{this.questions.set(await firstValueFrom(this.http.post<Question[]>('/api/questions/generate',{template_id:this.templateId(),query:this.query(),difficulty:this.difficulty(),bloom_level:this.bloom(),candidate_count:this.count()},{headers:this.headers()})));this.notice.set(`${this.questions().length} questions are ready for review.`);await this.loadUsage()}catch(e:any){this.notice.set(e?.error?.detail||'Generation could not be completed. Add indexed learning material, then try again.')}finally{this.generating.set(false)}} protected openFeedback(q:Question){this.ratingQuestion.set(q);this.rating.set(5);this.area.set('');this.feedbackNote.set('')} protected async sendFeedback(){const q=this.ratingQuestion();if(!q)return;if(this.rating()<3&&!this.area()){this.notice.set('Choose what needs improving before submitting a low rating.');return}try{await firstValueFrom(this.http.post(`/api/questions/${q.id||'generated'}/feedback`,{rating:this.rating(),improvement_area:this.area()||null,comment:this.feedbackNote()||null},{headers:this.headers()}));this.notice.set('Feedback saved. Your next questions will reflect it.');this.ratingQuestion.set(null)}catch{this.notice.set('Save the question first before rating it.')}} protected async saveProfile(){try{this.setUser(await firstValueFrom(this.http.patch<User>('/api/auth/me',{display_name:this.name(),bio:this.bio()||null,institution:this.institution()||null},{headers:this.headers()})));this.notice.set('Profile updated.')}catch{this.notice.set('Profile could not be updated.')}} protected async changePassword(){try{await firstValueFrom(this.http.post('/api/auth/me/password',{current_password:this.currentPassword(),new_password:this.newPassword()},{headers:this.headers()}));this.notice.set('Password updated successfully.')}catch{this.notice.set('Password could not be updated. Check your current password.')}}
}
